TARGET  := alertcenter.exe
INCS = -I ../network -I ../utils
LIBS = -L ../utils -lutils -L ../network -lnetwork  -lev -lhiredis -ljansson -lmpdec -lcurl -L /Users/bitcocohe/Github/depends/lib -lssl -lcrypto  -lm
include ../makefile.inc
