TARGET  := alertcenter.exe
INCS = -I ../network -I ../utils
LIBS = -L ../utils -lutils -L ../network -lnetwork  -lev -lhiredis -ljansson -lmpdec -lcurl -L /usr/local/Cellar/openssl/1.0.2r/lib -lssl -lcrypto  -lm
include ../makefile.inc
