TARGET  := matchengine.exe
INCS = -I ../network -I ../utils
LIBS = -L ../utils -lutils -L ../network -lnetwork  -lev -ljansson -lmpdec -lmysqlclient -lz -lrdkafka -L /usr/local/Cellar/openssl/1.0.2r/lib -lssl -lcrypto -lhiredis  -lm -lpthread -ldl
include ../makefile.inc
