TARGET  := matchengine.exe
INCS = -I ../network -I ../utils
LIBS = -L ../utils -lutils -L ../network -lnetwork  -lev -ljansson -lmpdec -lmysqlclient -lz -lrdkafka -L /Users/bitcocohe/Github/depends/openssl/lib -lssl -lcrypto -lhiredis  -lm -lpthread -ldl
include ../makefile.inc
