TARGET  := accesshttp.exe
INCS = -I ../network -I ../utils
LIBS = -L ../utils -lutils -L ../network -lnetwork  -lev -ljansson -lmpdec -lrdkafka -lz  -L /Users/bitcocohe/Github/depends/lib -lssl -lcrypto -lhiredis -lm -lpthread -ldl
include ../makefile.inc
